
# Add source files here
EXECUTABLE      := compiler_demosaic
# Cuda source files (compiled with cudacc)
CUFILES         := demosaic.cu cudaCom.cu
# C/C++ source files (compiled with gcc / c++)
CCFILES         := \
        demosaic_gold.cpp

USECUFFT        := 1
################################################################################
# Rules and targets

include ../../common/common.mk

