
# Add source files here
EXECUTABLE      := compiler_imregionmax
# Cuda source files (compiled with cudacc)
CUFILES         := imregionmax.cu cudaCom.cu
# C/C++ source files (compiled with gcc / c++)
CCFILES         := \
        imregionmax_gold.cpp

USECUFFT        := 1
################################################################################
# Rules and targets

include ../../common/common.mk

